//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class candado
    {
        public long id { get; set; }
        public string serial { get; set; }
        public string combinacion { get; set; }
        public bool disponible { get; set; }
        public long Locker_Caballero_id { get; set; }
        public long Locker_Dama_id { get; set; }
    
        public virtual locker_caballeros locker_caballeros { get; set; }
        public virtual locker_damas locker_damas { get; set; }
    }
}
