//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class dia_festivos
    {
        public long id { get; set; }
        public int dia { get; set; }
        public int mes { get; set; }
        public string descripcion { get; set; }
        public string tipo { get; set; }
    }
}
