//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class horarios
    {
        public string codigo { get; set; }
        public string descripcion { get; set; }
        public string tipo { get; set; }
        public string hora_entrada { get; set; }
        public string hora_salida { get; set; }
        public string periodo_descanso { get; set; }
        public string periodo_activo { get; set; }
        public string periodo_total { get; set; }
        public bool permitir_salida { get; set; }
        public bool remarcaje { get; set; }
        public string observacion { get; set; }
        public bool disponible { get; set; }
        public long Departamento_id { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public bool nocturno { get; set; }
    
        public virtual Departamentos Departamentos { get; set; }
    }
}
