//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class model_has_permissions
    {
        public int permission_id { get; set; }
        public string model_type { get; set; }
        public long model_id { get; set; }
    
        public virtual permissions permissions { get; set; }
    }
}
